# NumPy 

NumPy è l'abbreviazione di Numerical Python ed è il pacchetto più importante per il calcolo scientifico in Python.

+ Numpy migliora la manipolazione di array mono e multidimensionali ed offre un rango vasto di funzioni matematiche. 

+ Per agire sui vettori e sulle matrici si ricorre a loop che iterano su tutti o parte dei loro elementi, dunque all'istruzione for. Numpy offre strumenti progettati per fare a meno dell'uso di for in maniera esplicita. 

---------------------------------------------------------------------------------------

## Array
Un array è una struttura dati che può contenere una collezione ordinata di elementi, tutti dello stesso tipo, e che consente accesso rapido tramite indici numerici.

Python non ha un tipo nativo chiamato "array" come in altri linguaggi (come C o Java). Tuttavia, ci sono due principali modi per lavorare con array.

---------------------------------------------------------------------------------------

## Liste (list)
Sono la struttura dati più usata in Python per contenere elementi ordinati. Possono contenere tipi diversi, anche se spesso vengono usate come array. \
Le liste non impongono che tutti gli elementi siano dello stesso tipo.

In [1]:
numeri = [1, 2, 3, 4, 5]
print(numeri[2])

3


## Array del modulo array
Se abbiamo bisogno di un array più efficiente in termini di memoria, possiamo usare il modulo array della libreria standard.

* 'i' indica il tipo di dato (interi).
* Tutti gli elementi devono essere dello stesso tipo.

In [2]:
import array

numeri = array.array('i', [1, 2, 3, 4, 5])  
print(numeri[2]) 

3


# Array con NumPy
Per uso scientifico o matematico, si usa la libreria NumPy, che fornisce array multidimensionali e ottimizzati:

In [5]:
import numpy as np

numeri = np.array([1, 2, 3, 4, 5])
print(numeri[2])

3


# Liste e Array

Liste ed array hanno una sintassi simile.
1. I loro elementi sono ordinati, mutevoli e possono memorizzare elementi duplicati. 
2. Consentono indicizzazione, slicing e iterazione.

#### Tutti i programmi che utilizzano numpy devono importare il package:

`import numpy as np`

In [7]:
import numpy as np 

# creiamo una lista [1,1,2,2,3,3]
lista_1 =[1,1,2,2,3,3]

In [8]:
# creiamo un array 
array_1 = np.array([1,1,2,2,3,3])

In [9]:
print(array_1)

[1 1 2 2 3 3]


# Esercizio
Creiamo un array da `[4, 77, 2, 98]` e visualizziamolo. 

|<br>
|<br>
|<br>
|<br>
|<br>
|<br>
|<br>
|<br>

In [10]:
array_test = np.array([4,77,2,98])
print(array_test)

[ 4 77  2 98]


## Creiamo un array con una variabile

In [12]:
vendite=[3,6,44,1234,11, 11]

vendite_array=np.array(vendite)

print(vendite_array)

[   3    6   44 1234   11   11]


## Differenze tra array e liste
+ Le liste sono strutture dati integrate, possono contenere elementi di tipi diversi, le dimensioni delle liste sono flessibili, poiché si espandono man mano che aggiungiamo nuovi elementi.
+ Gli array devono essere importati, possono contenere solo dati dello stesso tipo, ad esempio solo interi o solo stringhe, una volta definita la dimensione di un array, questa rimane fissa e non può essere espansa. 

In [18]:
lista = ["pico",4,5]

In [19]:
lista.append("machine learning")
print(lista)

['pico', 4, 5, 'machine learning']


In [22]:
import numpy as np
array = np.array([3,4,5])
print(array)

[3 4 5]


## Gli array numpy più efficienti
Gli array numpy consumano meno memoria, memorizzano i dati in modo molto compatto e sono più efficienti per la memorizzazione di grandi quantità di dati.
+ una lista Python e un array NumPy con 1.000 elementi: l'array NumPy consuma sei volte meno memoria rispetto alla lista. 
+ Gli elementi di NumPy richiedono solo la memoria per memorizzare i valori, ad esempio, quattro byte per un valore intero.
+ Le liste devono memorizzare molte più informazioni come il valore dell'oggetto, il tipo di oggetto, il conteggio dei riferimenti e la dimensione di quel valore intero.

##  Gli array sono più veloci rispetto alle liste Python.
+ Se vogliamo moltiplicare ciascun elemento di una lista per un numero, dobbiamo utilizzare un ciclo `for`. 
+ Con un array numpy, possiamo semplicemente moltiplicare l'intero array usando l'operazione di moltiplicazione, che si occuperà di moltiplicare ciascun elemento. 

Quando confrontiamo il tempo necessario per questa operazione su 10.000 interi, la lista Python con il ciclo for impiega in media un millisecondo, mentre l'array numpy completa la stessa operazione in un centesimo di millisecondo, rendendolo 100 volte più veloce delle liste.

In [26]:
lista = [2,3,5]
[i*5 for i in lista]

[10, 15, 25]

In [27]:
import numpy as np
array = np.array([2,3,5])
array * 5

array([10, 15, 25])

## `np.array`
+ `np.array` è una funzione che utilizzo per creare un array;
+ con la funzione `np.array` si creano array da liste o ennuple, inizianizzandone gli elementi a proprio piacimento. 
+ le tuple sono delle ennuple ovvero sono delle collezioni ordinate e non modificabili, sono sequenze che possono contenere valori duplicati. A differenza delle strighe possono contenere anche valori eterogenei.

In [28]:
import numpy as np
pico_dataset = np.array([4,5,6])
print(pico_dataset)

[4 5 6]


## Array bidimensionale
+ In un array o matrice bidimensionale i dati sono organizzati per righe e per colonne, come se fossero inseriti in una tabella. 
+ Per la sua memorizzazione possiamo utilizzare una lista, specificando il numero di componenti per ciascuna delle due dimensioni che la costituiscono:

In [30]:
array_lista = [[111],[555],[666],[777]]
print(array_lista)

[[111], [555], [666], [777]]


L'oggetto referenziato da `array_lista` è ancora una lista e contiene 4 righe e 3 colonne per un totale di 12 elementi:
+ per accedere a ciascuno di essi, si utilizzano due indici: il primo  specifica la riga da 0 a r-1, il secondo la colonna da 0 a c-1.
+ r e c sono il numero di righe e il numero di colonne.
+ per fare riferimento ad un elemento, si fa seguire al nome della lista il numero della riga meno uno ed il nome della colonna meno uno, entrambi racchiusi tra parentesi quadre.

In [36]:
array[1] #si riferisce alla seconda sottolista

[555]

In [37]:
array[1][0]

555

## Creazione di array

In [1]:
import numpy as np 
c=5; r=3; p=2

## Inizializzo un array con tutti gli elementi a zero.

In [2]:
mat1=np.zeros((p,r,c))
mat1

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

## Inizializzo un array con tutti gli elementi ad uno. 

In [5]:
mat2=np.ones((p,r,c))
mat2

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

## Inizializza un array vuoto

In [6]:
mat3=np.empty((p,r,c))
mat3

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

## Esercitazione
Crea un array con:
* d = 2; prima dimensione, quanti array 2D sono presenti
* r = 6; seconda dimensione, quante righe ha ogni array 2D
* c = 3; terza dimensione, quante colonne ha ogni riga

Crealo a uno e zero. 

|<br>
|<br>
|<br>
|<br>
|<br>
|<br>
|<br>
|<br>

In [7]:
d = 2
r = 4
c = 3

import numpy as np
esercitazione = np.ones((d,r,c))
esercitazione

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [55]:
esercitazione_zero = np.zeros((d,r,c))
esercitazione_zero

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

## Tipo `ndarray`
Gli array sono di tipo `numpy.ndarray` ed i loro elementi sono numeri di tipo `ndtype`.

`Ndarray` è l'abbreviazione di **N-dimensional array** e si tratta di **array multi-dimensionali**, ottimizzati per eseguire operazioni matematiche e manipolazioni dati in modo efficiente. 

In [56]:
mat1=np.zeros((p,r,c))
mat1

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

## Sintassi
`numpy.zeros(shape, dtype)`:
* shape è una ennupla con tanti valori quante le dimensioni: ogni valore ne indica il numero di elementi lungo quella dimensione. 
* ogni dimensione è chiamata axis;
* il numero degli axis è detto rank. 

## `np.full` - crea un nuovo array pieno di valore
`np.full(shape, fill_value)`
* `shape`: una tupla che definisce la forma dell'array;
* `fill_value`: il valore con cui riempire l'array.

In [59]:
import numpy as np

# Crea un array 2x3 pieno di 7
a = np.full((2, 3), 7)

print(a)

[[7 7 7]
 [7 7 7]]


## `np.full_like` 
Crea un nuovo array con la stessa forma e tipo di un array esistente, ma riempito con un valore specificato.

`np.full_like(array_esistente, valore)`
* Copia forma e tipo da array_esistente.
* Riempi ogni elemento con valore.

In [61]:
import numpy as np

# Array di partenza
a = np.array([[1, 2, 3], [4, 5, 6]])

# Crea un array uguale in forma e tipo, ma pieno di 99
b = np.full_like(a, 99)

print(b)

[[99 99 99]
 [99 99 99]]


# Esercitazione 1 - `np.full()`
Crea una tabella 4X5 piena del numero 8 usando `np.full()`

|<br>
|<br>
|<br>
|<br>
|<br>
|<br>
|<br>
|<br>

In [8]:
import numpy as np

# Crea un array 4x5 pieno di 8
tabella = np.full((4, 5), 8)

print("Tabella piena di 8:")
print(tabella)

Tabella piena di 8:
[[8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]]


# Esercitazione 2 - `np.full_like()`
Dato un array esistente, `esistente = np.array([[3, 7, 1], [0, 5, 2]])` crea un array con stessa forma e tipo, ma pieno di -1.
|<br>
|<br>
|<br>
|<br>
|<br>
|<br>
|<br>
|<br>

In [63]:
import numpy as np

# Array di partenza
esistente = np.array([[3, 7, 1], [0, 5, 2]])

# Crea array della stessa forma e tipo, pieno di -1
nuovo = np.full_like(esistente, -1)

print("Array originale:")
print(esistente)

print("Array pieno di -1 con full_like:")
print(nuovo)

Array originale:
[[3 7 1]
 [0 5 2]]
Array pieno di -1 con full_like:
[[-1 -1 -1]
 [-1 -1 -1]]


# Funzione `np.array()` 
Con la funzione **np.array** si creano array da liste ed ennuple, inizializzandone gli elementi a proprio piacimento

In [58]:
import numpy as np
array_funzione = np.array([[1,4,4,5],[7,77,9,8]])
print(array_funzione)

[[ 1  4  4  5]
 [ 7 77  9  8]]


`np.array` trasforma liste ed ennuple in oggetti `ndarray`.

# `np.arange()`
Crea un array NumPy con valori numerici in sequenza e distanziati, simile alla funzione `range()`, ma restituisce un array NumPy.

`np.arange(start, stop, step)`

* start: valore iniziale (incluso)
* stop: valore finale (escluso)
* step: passo (opzionale, default = 1)

In [9]:
import numpy as np

a = np.arange(1, 10, 2)
print(a)

[1 3 5 7 9]


## Esercitazione con `np.arange()`
Crea un array NumPy con i numeri da 5 a 50 (escluso), con passo 5.
* Calcola la somma dei numeri dell’array.
* Trova il valore massimo.
|<br>
|<br>
|<br>
|<br>
|<br>
|<br>
|<br>
|<br>

In [10]:
import numpy as np

# 1. Crea l'array
numeri = np.arange(5, 50, 5)

# 2. Calcola la somma
somma = numeri.sum()

# 3. Trova il massimo
massimo = numeri.max()

# Stampa i risultati
print("Array:", numeri)
print("Somma:", somma)
print("Massimo:", massimo)


Array: [ 5 10 15 20 25 30 35 40 45]
Somma: 225
Massimo: 45


# `np.linspace()`
Crea un array NumPy con un numero fisso di valori equamente distribuiti tra un valore iniziale e un valore finale (incluso per default).

`np.linspace(start, stop, num=50)`

* **start**: valore iniziale;
* **stop**: valore finale;
* **num**: numero di valori da generare (default = 50);
* **endpoint=True**: se True (default), include anche stop.


In [11]:
import numpy as np

a = np.linspace(0, 1, 5)
print(a)

[0.   0.25 0.5  0.75 1.  ]


# Esercitazione `np.linspace()`

1. Crea 6 numeri equidistanti tra 10 e 20
2. Calcola:
- la differenza media tra i valori
- la media dei valori

3. Stampa tutto
|<br>
|<br>
|<br>
|<br>
|<br>
|<br>
|<br>
|<br>

In [71]:
import numpy as np

# 1. Creiamo 6 valori equidistanti tra 10 e 20
valori = np.linspace(10, 20, 6)

# 2. Differenza media tra valori (passo)
passo = valori[1] - valori[0]

# 3. Media dei valori
media = valori.mean()

# 4. Stampiamo i risultati
print("Valori:", valori)
print("Passo:", passo)
print("Media:", media)

Valori: [10. 12. 14. 16. 18. 20.]
Passo: 2.0
Media: 15.0


# Oggetti ndarray

L'oggetto istanziato dalla classe ndarray è una struttura dati omogenea e multidimensionale. 
+ Ogni dimensione **axis** ha una lunghezza, corrispondente al numero degli elementi.
+ **Shape** è la ennupla di interi contenente le lunghezze di tutti di axis.
+ **Size** è il numero totale di elementi presenti nell'array. 

In [12]:
import numpy as np 
array_nd=np.array([[1,2,0],[0,0,1],[1,2,0],[1,0,3]])
print(array_nd)

[[1 2 0]
 [0 0 1]
 [1 2 0]
 [1 0 3]]


Questo array numpy bidimensionale (2D) ha 2 axis, rispettivamente di lunghezza 4 e 3, la sua shape è la ennupla (4,3), la size è 12. 

In [72]:
import numpy as np 

array_nd = np.array([
    [1, 2, 0],
    [0, 0, 1],
    [1, 2, 0],
    [1, 0, 3]
])

print(array_nd)


[[1 2 0]
 [0 0 1]
 [1 2 0]
 [1 0 3]]


# `ndarray.type`
Tipo dei dati degli elementi dell'array.

In [74]:
array_nd.dtype

dtype('int64')

# `ndarray.ndim`
Numero di axis.

In [75]:
array_nd.ndim

2

# `ndarray.shape`
La forma dell'array descritta dalle sue dimensioni. E' un'ennupla che specifica le lunghezze di ogni dimensione(axis) dell'array, il numero di elementi di shape sarà pari al numero di axis, ndim.

In [76]:
array_nd.shape 

(4, 3)

`ndarray.size`
Numero degli elementi dell'array, uguale al prodotto degli elementi di shape. 

In [77]:
array_nd.size

12

# `ndarray.reshape`
`reshape` è un metodo che permette di cambiare la forma (shape) di un array senza cambiare i dati contenuti.
> Cambia il numero di righe e colonne (o dimensioni), purché il numero totale di elementi rimanga lo stesso.

`array.reshape(nuova_forma)`
`nuova_forma`: una tupla come `(righe, colonne)` oppure più dimensioni.


In [78]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6])
b = a.reshape((2, 3))  # 2 righe, 3 colonne

print("Array originale:", a)
print("Array trasformato:")
print(b)

Array originale: [1 2 3 4 5 6]
Array trasformato:
[[1 2 3]
 [4 5 6]]


# Esercitazione con `reshape`
2. 1. Crea un array 1D con i numeri da 1 a 12
Trasformalo in:
- array 3x4
- array 4x3
- array 2x6
3. Stampa tutte le versioni con `.shape`
|<br>
|<br>
|<br>
|<br>
|<br>
|<br>
|<br>
|<br>

In [79]:
import numpy as np

# 1. Array 1D
a = np.arange(1, 13)  # da 1 a 12

# 2. Diverse forme
a_3x4 = a.reshape((3, 4))
a_4x3 = a.reshape((4, 3))
a_2x6 = a.reshape((2, 6))

# 3. Stampa
print("Array 3x4:")
print(a_3x4)
print("Forma:", a_3x4.shape)

print("\nArray 4x3:")
print(a_4x3)
print("Forma:", a_4x3.shape)

print("\nArray 2x6:")
print(a_2x6)
print("Forma:", a_2x6.shape)

Array 3x4:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Forma: (3, 4)

Array 4x3:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Forma: (4, 3)

Array 2x6:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
Forma: (2, 6)


# Tipi di Array

La programmazione orientata agli array utilizza gli array multidimensionali chiamati ndarrays, dove "ND" sta per **N-dimensionale**. 

### Indicizzazione
L'indicizzazione degli array NumPy inizia da zero: il primo elemento ha indice zero e l'ultimo elemento ha indice n-1, dove n è la lunghezza dell'array o la dimensione.

* Ogni valore nell'array è di tipo int64, dove "int" indica il tipo di dato intero e "64" il numero di bit che rappresentano ogni numero.
* Gli array possono avere altri tipi di dato, come int32, interi senza segno, numeri a virgola mobile o numeri complessi.

In [81]:
import numpy as np

In [82]:
interi=np.array([10,20,30,40,50])
print(interi)

[10 20 30 40 50]


In [83]:
interi[2]

30

In [84]:
interi[0]=20
interi

array([20, 20, 30, 40, 50])

In [85]:
interi[0]=21.5 #tutti i dati devono essere dello stesso tipo, il float viene troncato
interi

array([21, 20, 30, 40, 50])

In [86]:
interi.dtype

dtype('int64')

# Array multidimensionali

L'array chiamato **ndarray** è l'oggetto centrale del pacchetto NumPy. 

+ Un array unidimensionale può essere visto come un vettore. 
+ Un array bidimensionale come una matrice. 
+ Un array tridimensionale come un tensore. 

In [87]:
import numpy as np

In [88]:
numeri_2d=np.array([[1,2,3,4,5],[6,7,8,9,10]]) 
numeri_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

Abbiamo creato un array 2D, ovvero una matrice con 2 righe e 5 colonne.

In [69]:
numeri_2d[1,0]

6

Abbiamo avuto accesso all'elemento dell'array `numeri_2d` che si trova:
* nella seconda riga - 1 gli indici partono da 0
* nella prima colonna - 0

In [70]:
numeri_2d[1,1]

7

# array 3D

In [94]:
multi_arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) #array 3D

In [95]:
multi_arr = np.array([
    [[1, 2, 3], [4, 5, 6]],       # Primo blocco (indice 0)
    [[7, 8, 9], [10, 11, 12]]     # Secondo blocco (indice 1)
])
multi_arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

#### Un array 3D è come una lista di array 2D.
In questo caso:
* 2 blocchi → prima dimensione (profondità)
* Ogni blocco ha 2 righe
* Ogni riga ha 3 colonne

In [96]:
multi_arr.shape

(2, 2, 3)

In [97]:
multi_arr[0, 1, 2]

6

* `multi_arr[0]` → primo blocco → `[[1, 2, 3], [4, 5, 6]]`
* `multi_arr[0, 1]` → seconda riga del primo blocco → `[4, 5, 6]`
* `multi_arr[0, 1, 2]` → terzo elemento della seconda riga del primo blocco → `6`

In [98]:
multi_arr[1,0,2]

9

In [99]:
multi_arr.size

12

In [78]:
multi_arr.dtype

dtype('int64')

# Creare Array dalle liste e da altre strutture Python
E' possibile costruire array direttamente da oggetti Python, come liste, tuple o liste di liste. 

In [100]:
import numpy as np

In [101]:
prima_lista=[1,2,3,4,5,6,7,8,9,10]

In [102]:
prima_lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [103]:
primo_array=np.array(prima_lista)
primo_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [104]:
seconda_lista=[1,2,3,-1.23, 50, 12800, 4.56] #lista con elementi diversi
seconda_lista

[1, 2, 3, -1.23, 50, 12800, 4.56]

In [105]:
secondo_array=np.array(seconda_lista) 
secondo_array

array([ 1.00e+00,  2.00e+00,  3.00e+00, -1.23e+00,  5.00e+01,  1.28e+04,
        4.56e+00])

Array ha automaticamente promosso tutti i numeri al tipo dell'elemento più generico della lista, che in questo caso è un numero a virgola mobile (Floating Point).

In [106]:
secondo_array.dtype

dtype('float64')

In [107]:
terza_lista=['Emiliano', 7777, 'Carver', 1944, 'Hugo', 1789] #contiene sia numeri che stringhe
terza_lista

['Emiliano', 7777, 'Carver', 1944, 'Hugo', 1789]

In [108]:
terzo_array=np.array(terza_lista) #U21 raccont che array è stringa unicode
terzo_array

array(['Emiliano', '7777', 'Carver', '1944', 'Hugo', '1789'], dtype='<U21')

### Il **valore dtype='<U21'** rappresenta il tipo di dato degli elementi di un array. 
Quando dtype è impostato su <U21, significa che:

+ Gli elementi sono stringhe Unicode (U):
+ Unicode è un sistema di codifica standard che consente di rappresentare testi in più lingue e simboli.
+ Il tipo U viene utilizzato per array di stringhe, assicurandosi che ogni elemento possa contenere caratteri Unicode.
+ La lunghezza massima è di 21 caratteri:
+ Ogni elemento dell'array può contenere stringhe di lunghezza massima pari a 21 caratteri.
+ Se una stringa più lunga viene inserita, sarà troncata.


> ## Quando creiamo un ndarray, tutti gli elementi diventano stringhe, poiché le stringhe sono considerate il tipo più generale.

## In NumPy, tutti gli elementi di un ndarray devono avere lo stesso tipo (dtype).

* Se crei un array con elementi misti (numeri e stringhe), NumPy cercherà un tipo comune in cui può convertire tutto senza perdita di informazione.
* La stringa è il tipo più "generale" (non perde dati da nessun altro tipo), quindi tutti gli elementi verranno convertiti in stringhe.

In [109]:
prima_tupla=(5,10,15,20,25,30)
prima_tupla

(5, 10, 15, 20, 25, 30)

Abbiamo creato un array a partire da una tupla.
+ Le tuple sono sequenze immutabili, il che significa che, una volta definite, i singoli elementi non possono essere modificati.
+ La differenza principale tra una lista e una tupla è che una tupla è racchiusa tra parentesi tonde.

In [110]:
array_da_prima_tupla=np.array(prima_tupla)
array_da_prima_tupla

array([ 5, 10, 15, 20, 25, 30])

In [111]:
array_da_prima_tupla.dtype

dtype('int64')

In [112]:
lista_multi_dim=[[[0,1,2],[3,4,5],[6,7,8], [9,10,11]]]
lista_multi_dim

[[[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]]]

In [113]:
array_da_lista_multi_dim=np.array(lista_multi_dim)
array_da_lista_multi_dim

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]])

# Creazione intrinseca di array NumPy

NumPy offre alcune funzioni utili per creare array riempiti con valori specifici. 


In [114]:
import numpy as np

## Funzione `arange` 
Se passiamo un intero come argomento a arange, otterremo un array unidimensionale di interi che inizia da zero e termina prima del valore intero passato come parametro.

In [115]:
interi_array=np.arange(10)
interi_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [116]:
interi_secondo_array=np.arange(100,130)
interi_secondo_array

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129])

Passiamo tre argomenti: il primo definisce il valore iniziale, il secondo il valore finale e il terzo definisce lo step. \
Lo step viene usato per saltare valori. 

In [117]:
interi_terzo_array=np.arange(100,201,8)
interi_terzo_array

array([100, 108, 116, 124, 132, 140, 148, 156, 164, 172, 180, 188, 196])

# Esercitazione `np.arange`
1. Creare un array con numeri da 50 a 150 con passo 7
2. Visualizzare:
* La forma dell’array
* Il numero di elementi
* Il primo e l’ultimo elemento
3. Calcolare:
* La somma di tutti i numeri
* La media dei valori
* Quanti numeri sono divisibili per 5
|<br>
|<br>
|<br>
|<br>
|<br>
|<br>
|<br>
|<br>

In [118]:
import numpy as np

# 1. Crea array da 50 a 150 (escluso 151), passo 7
interi_array = np.arange(50, 151, 7)

# 2. Informazioni base
print("Array:", interi_array)
print("Forma:", interi_array.shape)
print("Numero di elementi:", interi_array.size)
print("Primo elemento:", interi_array[0])
print("Ultimo elemento:", interi_array[-1])

# 3. Calcoli
somma = interi_array.sum()
media = interi_array.mean()
multipli_di_5 = np.count_nonzero(interi_array % 5 == 0)

# 4. Risultati
print("Somma:", somma)
print("Media:", media)
print("Multipli di 5:", multipli_di_5)


Array: [ 50  57  64  71  78  85  92  99 106 113 120 127 134 141 148]
Forma: (15,)
Numero di elementi: 15
Primo elemento: 50
Ultimo elemento: 148
Somma: 1485
Media: 99.0
Multipli di 5: 3


# Funzione linspace
Per creare un array di numeri a virgola mobile con valori decimali equidistanti, la scelta migliore è la funzione linspace. \
`linspace` accetta solitamente tre argomenti:

+ start, il valore iniziale della sequenza,
+ stop, il valore finale della sequenza,
+ num, opzionale, che rappresenta il numero di campioni da generare.

In [119]:
primo_mobile_array=np.linspace(10,40) #di base 50 punti
primo_mobile_array

array([10.        , 10.6122449 , 11.2244898 , 11.83673469, 12.44897959,
       13.06122449, 13.67346939, 14.28571429, 14.89795918, 15.51020408,
       16.12244898, 16.73469388, 17.34693878, 17.95918367, 18.57142857,
       19.18367347, 19.79591837, 20.40816327, 21.02040816, 21.63265306,
       22.24489796, 22.85714286, 23.46938776, 24.08163265, 24.69387755,
       25.30612245, 25.91836735, 26.53061224, 27.14285714, 27.75510204,
       28.36734694, 28.97959184, 29.59183673, 30.20408163, 30.81632653,
       31.42857143, 32.04081633, 32.65306122, 33.26530612, 33.87755102,
       34.48979592, 35.10204082, 35.71428571, 36.32653061, 36.93877551,
       37.55102041, 38.16326531, 38.7755102 , 39.3877551 , 40.        ])

In [100]:
secondo_mobile_array=np.linspace(10,20,10)
secondo_mobile_array

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

## È importante distinguere la differenza tra `arange` e `linspace`

+ `arange` utilizza come terzo argomento la dimensione dello step
+ `linspace` utilizza il numero di punti da generare.

---------------------------------------------------------------------------------------------------------------

# `np.random`

`np.random` è un modulo di NumPy che permette di generare numeri casuali o pseudo-casuali. \
Viene usato spesso in:

* simulazioni
* test
intelligenza artificiale
* machine learning
* giochi o estrazioni

# Funzione `rand`
Ndarrays con dati distribuiti casualmente vengono utilizzati in algoritmi numerici e di machine learning.

* Utilizziamo la libreria random di NumPy e la funzione rand.
* Questa funzione crea un array delle dimensioni specificate, popolandolo con numeri a virgola mobile distribuiti uniformemente nell'intervallo da 0 a 1.

`np.random.rand(10)` genera un array NumPy contenente 10 numeri casuali (float) compresi tra 0.0 e 1.0, distribuiti uniformemente.

* L’array ha forma (10,), cioè un array 1D di 10 elementi.
* I valori sono float64 per default.
* Tutti i valori sono in `[0.0, 1.0)` (il valore 1 è escluso).

In [13]:
primo_rand_arr=np.random.rand(10) # numeri casuali distribuiti uniformemente
print(primo_rand_arr)                    # hanno la stessa probabilità di essere generati

[0.85340211 0.94218878 0.93416505 0.90146941 0.87159512 0.78726165
 0.06490053 0.51548836 0.28412978 0.23781469]


Creo un array NumPy 2D (4x4) pieno di numeri casuali float tra 0.0 e 1.0, distribuiti uniformemente.

* Forma: (4, 4) → 4 righe, 4 colonne
* Valori: float64, casuali, nell’intervallo `[0.0, 1.0)`
* Tipo di distribuzione: uniforme, cioè ogni valore ha la stessa probabilità

In [122]:
secondo_rand_arr=np.random.rand(4,4)
secondo_rand_arr

array([[0.68441043, 0.06182365, 0.39392334, 0.99225413],
       [0.69644679, 0.32646614, 0.19851041, 0.9195466 ],
       [0.29337282, 0.8803582 , 0.37731579, 0.09103353],
       [0.4536224 , 0.42603852, 0.14934979, 0.66936206]])

# Funzione Randint
Possiamo usare per creare un array di numeri interi casuali. \
Questa funzione accetta tre argomenti:

+ Il primo è il valore intero minimo (inclusivo),
+ Il secondo è il valore intero massimo (esclusivo),
+ Il terzo è il numero di elementi da generare.

In [123]:
terzo_rand_arr=np.random.randint(0,100,20)
terzo_rand_arr

array([93, 71, 94,  2, 88, 46, 68, 10, 46, 20, 46, 96, 40, 86, 39, 71, 78,
       75, 59, 62])

# Esercitazione - array base
Crea un array 1D con 6 numeri casuali tra 0 e 1 e stampalo.
|<br>
|<br>
|<br>
|<br>
|<br>
|<br>
|<br>
|<br>

In [125]:
import numpy as np

arr = np.random.rand(6)
print("Array casuale:", arr)

Array casuale: [0.45616258 0.52490012 0.60204524 0.27896417 0.88798346 0.55770387]


# Esercitazione - massimo e minimo
Genera un array 4x4 casuale e trova:

* il valore massimo
*il valore minimo
|<br>
|<br>
|<br>
|<br>
|<br>
|<br>
|<br>
|<br>

In [126]:
import numpy as np

array_4x4 = np.random.rand(4, 4)

print("Array 4x4:")
print(array_4x4)

print("Massimo:", np.max(array_4x4))
print("Minimo:", np.min(array_4x4))


Array 4x4:
[[0.27609294 0.29356948 0.55098281 0.98338898]
 [0.26066544 0.58590511 0.34158615 0.81980665]
 [0.89447516 0.95593303 0.708933   0.68397403]
 [0.40315775 0.36164249 0.34617263 0.08306437]]
Massimo: 0.9833889782695632
Minimo: 0.0830643709940635


# Esercitazioni 
1. Genera un array 1D di 5 interi casuali tra 1 e 100
2. Calcola la media e quanti valori sono ≥ 50
|<br>
|<br>
|<br>
|<br>
|<br>
|<br>
|<br>
|<br>

In [141]:
import numpy as np

arr = np.random.randint(1, 101, size=5)
print("Array:", arr)

print("Media:", arr.mean())
print("≥ 50:", np.count_nonzero(arr >= 50))


Array: [ 7 84 33 22 56]
Media: 40.4
≥ 50: 2


# Funzione fill e full. 
La **funzione `fill`** viene usata per riempire un array già esistente con un valore specifico. \
La **funzione `full`** può essere utilizzata per creare direttamente array unidimensionali o bidimensionali con un valore specifico. 

1. Per utilizzare la funzione fill, dobbiamo prima creare un array vuoto.
2. Usiamo la funzione empty, che crea un array con elementi non inizializzati.
3. `.empty()` non inizializza i valori: `np.empty(10, dtype=int)` crea un array senza inizializzare i valori, quindi:
* la memoria viene riservata
* ma i contenuti sono casuali/spazzatura (numeri residui già presenti in RAM)
* può contenere numeri strani o casuali

In [136]:
primo_full_array=np.empty(10, dtype=int)
primo_full_array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [137]:
primo_full_array=np.empty(10)
primo_full_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [138]:
primo_full_array=np.empty(10, dtype=int)
primo_full_array.fill(9)
primo_full_array

array([9, 9, 9, 9, 9, 9, 9, 9, 9, 9])

In [139]:
primo_full_array=np.full(5,10)
primo_full_array

array([10, 10, 10, 10, 10])

In [140]:
secondo_full_array=np.full((4,5),8)
secondo_full_array

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

# Aggiungere, eliminare e ordinare elementi di un array. 
Per aggiungere elementi a un array, possiamo usare due funzioni: 
+ La funzione `insert` ci consente di specificare l'indice in cui vogliamo aggiungere un elemento.
+ La funzione `append` aggiunge il valore alla fine dell'array.


## Funzione `insert`
`np.insert()` restituisce un nuovo array con uno o più valori inseriti in una posizione specifica.
`np.insert(array, posizione, valore)`

- `array`: l’array di partenza
- `posizione`: indice dove inserire
- `valore`: elemento o lista di elementi da inserire

`np.insert()` NON modifica l’array originale: crea un nuovo array con l’inserimento.


In [14]:
import numpy as np
primo_array = np.array([1,2,3,5])
primo_array

array([1, 2, 3, 5])

In [15]:
nuovo_primo_array=np.insert(primo_array,3,4)
nuovo_primo_array

array([1, 2, 3, 4, 5])

In [16]:
import numpy as np

a = np.array([10, 20, 30, 40])

nuovo = np.insert(a, 2, 99)  # inserisce 99 tra 20 e 30

print("Originale:", a)
print("Modificato:", nuovo)


Originale: [10 20 30 40]
Modificato: [10 20 99 30 40]


# Esercizio
* Crea un array `[1, 2, 3, 4, 5]`
* Inserisci il numero 100 in posizione 0 (inizio)
* Inserisci il numero 999 alla fine
* Stampa il nuovo array
|<br>
|<br>
|<br>
|<br>
|<br>
|<br>
|<br>
|<br>

In [149]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])

a_inizio = np.insert(a, 0, 100)
a_fine = np.insert(a_inizio, len(a_inizio), 999)

print("Array finale:", a_fine)


Array finale: [100   1   2   3   4   5 999]


## Funzione `append`
`np.append()` aggiunge uno o più valori alla fine di un array, restituendo un nuovo array con gli elementi aggiunti.
`np.append(array, valori)`

* `array`: l’array originale
* `valori`: singolo valore o lista/array di valori da aggiungere alla fine

Come `insert()`, anche `append()` non modifica l'array originale: restituisce un nuovo array.

In [151]:
secondo_array=np.array([1,2,3,4])
secondo_array

array([1, 2, 3, 4])

In [152]:
nuovo_secondo_array=np.append(secondo_array, 5)
nuovo_secondo_array

array([1, 2, 3, 4, 5])

In [153]:
import numpy as np

a = np.array([1, 2, 3])
nuovo = np.append(a, 4)

print("Originale:", a)
print("Dopo append:", nuovo)

Originale: [1 2 3]
Dopo append: [1 2 3 4]


# Esercitazione
1. Crea un array con `[10, 20, 30]`
2. Aggiungi 40 alla fine
3. Aggiungi anche 50 e 60
4. Stampa l’array finale
|<br>
|<br>
|<br>
|<br>
|<br>
|<br>
|<br>
|<br>

In [154]:
import numpy as np

a = np.array([10, 20, 30])

a = np.append(a, 40)
a = np.append(a, [50, 60])

print("Array finale:", a)


Array finale: [10 20 30 40 50 60]


# Funzione `delete`
`np.delete()` restituisce un nuovo array con uno o più elementi eliminati.
`np.delete(array, indice)`

* `array`: l’array di partenza;
* `indice`: l'indice (o gli indici) dell'elemento da eliminare.
* Come `insert()` e `append()`, anche `delete()` non modifica l’array originale.

Possiamo anche eliminare:
* più indici: `np.delete(a, [1, 3])`
* righe o colonne in array 2D, specificando `axis=0` (righe) o `axis=1` (colonne)

In [155]:
terzo_array=np.array([1,2,3,4,5])
terzo_array

array([1, 2, 3, 4, 5])

In [156]:
del_terzo_array=np.delete(terzo_array,2)
del_terzo_array

array([1, 2, 4, 5])

In [157]:
import numpy as np

a = np.array([10, 20, 30, 40, 50])

b = np.delete(a, 2)  # elimina il valore con indice 2 (cioè 30)

print("Originale:", a)
print("Senza 30:", b)

Originale: [10 20 30 40 50]
Senza 30: [10 20 40 50]


## Eliminare righe o colonne in array 2D
`np.delete(array, indici, axis)`
* `axis=0` → elimina righe
* `axis=1` → elimina colonne


In [159]:
import numpy as np

matrice = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])


In [160]:
matrice_senza_riga = np.delete(matrice, 1, axis=0)
print("Senza seconda riga:")
print(matrice_senza_riga)


Senza seconda riga:
[[1 2 3]
 [7 8 9]]


In [161]:
matrice_senza_colonna = np.delete(matrice, 0, axis=1)
print("Senza prima colonna:")
print(matrice_senza_colonna)

Senza prima colonna:
[[2 3]
 [5 6]
 [8 9]]


# Esercitazione - 1
1. Crea un array `[5, 10, 15, 20, 25, 30]`
2. Elimina:
* l’elemento con indice 0
* poi l’elemento con indice 3 (contando dopo la prima rimozione!)
3. Stampa il risultato finale
|<br>
|<br>
|<br>
|<br>
|<br>

In [162]:
import numpy as np

a = np.array([5, 10, 15, 20, 25, 30])

# Elimina primo elemento (indice 0)
a = np.delete(a, 0)  # → [10 15 20 25 30]

# Ora elimina l'elemento in posizione 3 (cioè 25)
a = np.delete(a, 3)

print("Array finale:", a)


Array finale: [10 15 20 30]


# Esercitazione - 2
1. Crea una matrice 4x4 con numeri da 1 a 16 (usa `np.arange().reshape()`)
2. Elimina:
* la terza riga
* la seconda colonna
3. Stampa il risultato finale

|<br>
|<br>
|<br>
|<br>
|<br>
|<br>

In [163]:
import numpy as np

# 1. Crea la matrice 4x4
matrice = np.arange(1, 17).reshape(4, 4)
print("Matrice originale:")
print(matrice)

# 2. Elimina la terza riga (indice 2)
matrice_senza_riga = np.delete(matrice, 2, axis=0)
print("\nSenza la terza riga:")
print(matrice_senza_riga)

# 3. Elimina la seconda colonna (indice 1)
matrice_finale = np.delete(matrice_senza_riga, 1, axis=1)
print("\nSenza la seconda colonna:")
print(matrice_finale)


Matrice originale:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Senza la terza riga:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [13 14 15 16]]

Senza la seconda colonna:
[[ 1  3  4]
 [ 5  7  8]
 [13 15 16]]


# Funzione `sort`
`np.sort()` restituisce un nuovo array ordinato con gli elementi in ordine crescente.

Non modifica l’array originale.

## Esempio array 1D

In [170]:
import numpy as np

a = np.array([5, 2, 9, 1, 7])
ordinato = np.sort(a)

print("Originale:", a)
print("Ordinato:", ordinato)

Originale: [5 2 9 1 7]
Ordinato: [1 2 5 7 9]


## Esempio array 2D
Possiamo ordinare:
* per riga → `axis=1`
* per colonna → `axis=0`

In [173]:
matrice = np.array([[3, 1, 2], [9, 6, 4]])

# Ordina ogni riga
print(np.sort(matrice, axis=1))

# Ordina ogni colonna
print(np.sort(matrice, axis=0))


[[1 2 3]
 [4 6 9]]
[[3 1 2]
 [9 6 4]]


In [164]:
numeri_interi_array=np.random.randint(0,20,20)
numeri_interi_array
#abbiamo creato un array monodimensionale

array([13,  1, 18, 14,  9,  3,  1,  9,  8,  1,  4,  9,  1,  1, 10, 15,  2,
        3,  1, 13])

In [165]:
print(np.sort(numeri_interi_array))

[ 1  1  1  1  1  1  2  3  3  4  8  9  9  9 10 13 13 14 15 18]


In [166]:
numeri_interi_2dim_array=np.array([[3,2,5,7,4], [5,0,8,3,1]])
numeri_interi_2dim_array
#abbiamo creato un array bidimensionale che contiene due array monodimensionali

array([[3, 2, 5, 7, 4],
       [5, 0, 8, 3, 1]])

In [167]:
print(np.sort(numeri_interi_2dim_array))

[[2 3 4 5 7]
 [0 1 3 5 8]]


In [168]:
colori=np.array(['rosso', 'verde', 'giallo', 'arancione', 'marrone', 'blu'])
colori

array(['rosso', 'verde', 'giallo', 'arancione', 'marrone', 'blu'],
      dtype='<U9')

In [169]:
print(np.sort(colori))
#gli elementi sono ordinati in ordine alfabetico

['arancione' 'blu' 'giallo' 'marrone' 'rosso' 'verde']


# Esercitazione 
1. Crea un array NumPy con `[10, 4, 8, 2, 6]`
2. Ordinalo in ordine crescente
3. Stampa il valore minimo e massimo dopo l’ordinamento

|<br>
|<br>
|<br>
|<br>
|<br>

In [174]:
import numpy as np

a = np.array([10, 4, 8, 2, 6])
ordinato = np.sort(a)

print("Array ordinato:", ordinato)
print("Minimo:", ordinato[0])
print("Massimo:", ordinato[-1])


Array ordinato: [ 2  4  6  8 10]
Minimo: 2
Massimo: 10


# Copie
Le copie di array in NumPy, un argomento molto importante per evitare modifiche involontarie agli array originali.

1. Copia reale - `np.copy()`o`.copy()`\
Crea un nuovo array indipendente. Modificare `b` non cambia `a`.

In [17]:
import numpy as np

a = np.array([1, 2, 3])
b = a.copy()

b[0] = 99

print("a:", a)  # → [1 2 3]
print("b:", b)  # → [99 2 3]


a: [1 2 3]
b: [99  2  3]


2. Copia per riferimento (default) - assegnazione diretta \
`a` e `b` puntano allo stesso array: se cambio uno, cambio l’altro!

In [175]:
a = np.array([1, 2, 3])
b = a  # <-- non è una vera copia!

b[0] = 99

print("a:", a)  # → [99 2 3]
print("b:", b)  # → [99 2 3]


a: [99  2  3]
b: [99  2  3]


# Esercizio 
1. Crea un array `[10, 20, 30]`
2. Crea una copia vera
3. Cambia un elemento della copia
4. Verifica che l’originale non sia cambiato

|<br>
|<br>
|<br>
|<br>
|<br>

In [185]:
import numpy as np

a = np.array([10, 20, 30])
b = a.copy()  # copia vera

b[1] = 99

print("Originale a:", a)
print("Copia modificata b:", b)


Originale a: [10 20 30]
Copia modificata b: [10 99 30]


In [179]:
m=np.array([[1,2,0,8],[3,0,0,3],[1,6,2,0]])
m

array([[1, 2, 0, 8],
       [3, 0, 0, 3],
       [1, 6, 2, 0]])

In [180]:
m1=m #copia di riferimento
m1

array([[1, 2, 0, 8],
       [3, 0, 0, 3],
       [1, 6, 2, 0]])

In [181]:
m1[1,2]=99
m1

array([[ 1,  2,  0,  8],
       [ 3,  0, 99,  3],
       [ 1,  6,  2,  0]])

In [182]:
m

array([[ 1,  2,  0,  8],
       [ 3,  0, 99,  3],
       [ 1,  6,  2,  0]])

* Modificare un elemento m1 è esattamente la stessa cosa che modificare un elemento di m e viceversa. \
* L'assegnamento non copia l'oggetto e neppure i suoi dati: se dopo m1=m di domandiamo m is m1, vedremo che la risposta è True, infatti m ed m1 sono due nomi che fanno riferimento allo stesso oggetto. 


In [183]:
m==m1

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

# Funzione `id()`
La funzione `id(obj)` restituisce l’identificatore unico (indirizzo di memoria) di un oggetto.

Verifica se ID sono uguali ⇒ m e m1 puntano allo stesso array

In [186]:
print('id m', id(m))
print('id m1', id(m1))

id m 140242450295856
id m1 140242450295856


# Copy e View 

In Numpy, alcune funzioni restituiscono una copia `copy()`, mentre altre restituiscono una vista `view()`.
La differenza tra Copy e View è che Copy è un nuovo array, mentre View è una vista diversa dell'array originale.

* Copy è memorizzato fisicamente in un'altra posizione;
* View ci fornisce un riferimento con un nome diverso alla stessa posizione in memoria.

## `View`
Una view è una finestra sull’array originale: non crea una nuova copia dei dati, ma un riferimento a una parte della memoria dell’array originale.

* Leggera, veloce, ma modificabile: ogni modifica alla view si riflette sull’array originale.

In [187]:
import numpy as np

In [188]:
studenti_id_numero=np.array([1111,1212,1313,1414,1515,1616,1717,1818])
studenti_id_numero

array([1111, 1212, 1313, 1414, 1515, 1616, 1717, 1818])

In [189]:
studenti_id_numero_reg=studenti_id_numero
print('id studenti_id_numero ', id(studenti_id_numero))
print('studenti_id_numero_reg', id(studenti_id_numero_reg))

id studenti_id_numero  140242450322800
studenti_id_numero_reg 140242450322800


* Abbiamo stampato gli id di entrambi gli array e vediamo che i loro id sono gli stessi.
* Aggiorniamo il secondo array con un nuovo valore.

In [190]:
studenti_id_numero_reg[1]=2222
print(studenti_id_numero)
print(studenti_id_numero_reg)

[1111 2222 1313 1414 1515 1616 1717 1818]
[1111 2222 1313 1414 1515 1616 1717 1818]


* Entrambi gli array sono stati modificati, per cui le assegnazioni non creano una copia di un oggetto array.  * Qualsiasi modifica apportata si riflette nell'altro array.

> Adesso creiamo copia del nostro array e verifichiamone l'uguaglianza. 

In [191]:
studenti_id_numero_copy=studenti_id_numero.copy()
print(studenti_id_numero_copy)

[1111 2222 1313 1414 1515 1616 1717 1818]


In [46]:
print(studenti_id_numero_copy==studenti_id_numero)

[ True  True  True  True  True  True  True  True]


In [193]:
print('id studenti_id_numero', id(studenti_id_numero))
print('studenti_id_numero_copy', id(studenti_id_numero_copy))

id studenti_id_numero 140242450322800
studenti_id_numero_copy 140242458348112


> Abbiamo verificato gli id di entrambi gli array e vediamo che fanno riferimento a posizioni diverse in memoria. 

In [194]:
#modifichiamo l'array originale
studenti_id_numero[0]=1000

print('originale:', studenti_id_numero)
print('copia', studenti_id_numero_copy)

#Verifichiamo che l'array originale studendi_id_numero è cambiato 
#Non c'è alcuna modifica nell'array copia. 

originale: [1000 2222 1313 1414 1515 1616 1717 1818]
copia [1111 2222 1313 1414 1515 1616 1717 1818]


## Perchè accade questo?
* Copy crea un array completamente nuovo, e si dice che Copy "possiede" i dati. 
* Se apportiamo modifiche all'array originale, queste **non influenzano la Copy**. 
* E se apportiamo modifiche alla Copy, queste non influenzano l'array originale. Questo è anche chiamato **"deep Copy"**.



In [195]:
#creiamo una vista del nostro array
studenti_id_numero_vista=studenti_id_numero.view()

In [196]:
studenti_id_numero_vista[0]=2000

print('originale:', studenti_id_numero)
print('vista', studenti_id_numero_vista)

originale: [2000 2222 1313 1414 1515 1616 1717 1818]
vista [2000 2222 1313 1414 1515 1616 1717 1818]


* Entrambi gli array sono stati modificati. 
* La View non possiede i dati. 
* Quando apportiamo modifiche all'array originale, queste influenzano la View. 
* Quando apportiamo modifiche alla View, queste influenzano l'array originale.

# `base`
Un altro modo per verificare se un array possiede i propri dati in View e Copy è l'attributo base che ogni array NumPy ha. \
Restituisce None se l'array possiede i dati, poiché l'attributo base si riferisce all'oggetto originale. 

In [51]:
print(studenti_id_numero_copy.base)
print(studenti_id_numero_vista.base)

None
[2000 2222 1313 1414 1515 1616 1717 1818]


Per l'array copiato abbiamo ottenuto None, mentre per la View è stato restituito l'array originale, quindi non possiede i dati.

# Reshaping Arrays
Una delle funzioni più utili per array multidimensionali. \
`Reshaping` significa cambiare il numero di righe e colonne di un array senza modificare i dati.

Usi il metodo `.reshape()` per cambiare la forma.
`array.reshape(nuova_forma)` \
La nuova forma deve contenere lo stesso numero totale di elementi.

In [204]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6])
b = a.reshape((2, 3))  # 2 righe, 3 colonne

print("Array originale:", a)
print("Array reshaped:")
print(b)

Array originale: [1 2 3 4 5 6]
Array reshaped:
[[1 2 3]
 [4 5 6]]


In [197]:
import numpy as np

In [198]:
primo_array=np.arange(1,13)
primo_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [199]:
secondo_array=np.reshape(primo_array,(3,4))
secondo_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [200]:
terzo_array=np.reshape(primo_array,(6,2))
terzo_array

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [201]:
quinto_array=np.reshape(primo_array,(3,2,2))
print(quinto_array)
print('La dimensione del quinto array è', quinto_array.ndim)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
La dimensione del quinto array è 3


In [202]:
sesto_array=np.array([[1,2],[3,4],[5,6]])
sesto_array

array([[1, 2],
       [3, 4],
       [5, 6]])

# Esercitazione
1. Crea un array con i numeri da 1 a 12
2. Reshape in:
* 3 righe × 4 colonne
* 2 righe × 6 colonne
3. Stampa forma e contenuto

|<br>
|<br>
|<br>
|<br>
|<br>
|<br>

In [205]:
import numpy as np

a = np.arange(1, 13)

b = a.reshape((3, 4))
c = a.reshape((2, 6))

print("Forma 3x4:\n", b)
print("Forma 2x6:\n", c)


Forma 3x4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Forma 2x6:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


 Possiamo usare -1 per lasciare che NumPy calcoli una dimensione automaticamente:

In [203]:
settimo_array_flat=np.reshape(sesto_array, -1)
settimo_array_flat

array([1, 2, 3, 4, 5, 6])

# `flatten()`
`flatten()` restituisce una copia dell’array appiattito, cioè trasformato in 1D.
 * L’array risultante è indipendente dall’originale.
 
# `ravel()`
`ravel()` restituisce un array appiattito, ma se possibile come view (cioè senza copiare i dati).
* Se ravel() restituisce una view, modificare l’array 1D modifica anche quello originale.


In [206]:
import numpy as np

a = np.array([[1, 2], [3, 4]])

f = a.flatten()
r = a.ravel()

f[0] = 100
r[1] = 200

print("Originale:\n", a)
print("Flatten:", f)
print("Ravel:  ", r)


Originale:
 [[  1 200]
 [  3   4]]
Flatten: [100   2   3   4]
Ravel:   [  1 200   3   4]


* Modificare f non cambia a, ma modificare r sì (perché r è una view).

In [207]:
ottavo_array_flat=sesto_array.flatten()
print('ottavo array flat:', ottavo_array_flat)

ottavo array flat: [1 2 3 4 5 6]


In [208]:
nono_array_rav=sesto_array.ravel()
print('nono arrey flat:', nono_array_rav)

nono arrey flat: [1 2 3 4 5 6]


In [209]:
ottavo_array_flat[0]=100

In [210]:
nono_array_rav[0]=200

In [211]:
print('ottavo array flat:', ottavo_array_flat)
print('nono arrey flat:', nono_array_rav)
print('sesto array:', sesto_array)

ottavo array flat: [100   2   3   4   5   6]
nono arrey flat: [200   2   3   4   5   6]
sesto array: [[200   2]
 [  3   4]
 [  5   6]]


# Esercitazione 
1. Crea un array 3×2 con valori da 1 a 6
2. Usa sia `flatten()` che `ravel()`
3. Modifica il primo elemento di ciascuno
4. Stampa l’array originale

|<br>
|<br>
|<br>
|<br>
|<br>

In [212]:
import numpy as np

# 1. Crea array 3x2
a = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

# 2. Crea flatten (copia) e ravel (view)
flat = a.flatten()
rav = a.ravel()

# 3. Modifica entrambi
flat[0] = 100
rav[1] = 200

# 4. Stampa tutto
print("Array originale:")
print(a)

print("\nArray flatten (copia):", flat)
print("Array ravel (view):", rav)


Array originale:
[[  1 200]
 [  3   4]
 [  5   6]]

Array flatten (copia): [100   2   3   4   5   6]
Array ravel (view): [  1 200   3   4   5   6]


# Indexing e slicing

Uno dei maggiori vantaggi di NumPy è la possibilità di manipolare grandi quantità di valori senza dover scrivere cicli inefficienti. \
Per fare ciò, dobbiamo essere in grado di fare riferimento agli elementi degli array in molti modi diversi. 

# Indicizzazione
Non trarremmo vantaggio dall'utilizzo di array multidimensionali se non potessimo accedere agli elementi al loro interno e aggiornarli quando necessario:
* Questo si chiama indicizzazione degli array. 
* L’indicizzazione è il modo in cui accedi agli elementi di un array NumPy usando indici numerici, proprio come con le liste Python — ma molto più potente.
* Per indicizzare gli array, utilizziamo parentesi quadre. 
* Le parentesi quadre contengono l'indice o gli indici degli elementi che vogliamo che NumPy restituisca o assegni, e questa tecnica si chiama sottoscrittura.

In [213]:
import numpy as np

In [220]:
import numpy as np

a = np.array([10, 20, 30, 40, 50])

print(a[0])    # → 10 (primo elemento)
print(a[-1])   # → 50 (ultimo elemento)

10
50


In [221]:
b = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(b[0, 1])  # → 2 (riga 0, colonna 1)
print(b[1, 2])  # → 6 (riga 1, colonna 2)

2
6


In [222]:
c = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print(c[1, 0, 1])  # → 6 (blocco 1, riga 0, colonna 1)


6


In [214]:
duedim_arr=np.reshape(np.arange(12),(3,4))
duedim_arr
#array bidimensionale con 3 righe e 4 colonne

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [216]:
duedim_arr[1,1]
#selezioniamo un elemento nella seconda riga e nella seconda colonna

5

In [217]:
duedim_arr[1]
#in un array bidimensionale ho specificato un singolo indice

array([4, 5, 6, 7])

In [218]:
import numpy as np
tredim_array=np.reshape(np.arange(3*4*5),(3,4,5))
tredim_array
#ho creato array tridimensionale 3x4x5

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [219]:
tredim_array[0,2,3]

13

# Indicizzazione negativa
Un'altra funzionalità utile è l'**indicizzazione negativa**, che consente di accedere agli elementi a partire dalla fine dell'array. 

In [70]:
tredim_array[2,-1,-1]

59

Avrei ottenuto lo stesso senza l'uso esplicito dell'indice. 

# Slicing 
Lo slicing in NumPy, che è una tecnica fondamentale per selezionare porzioni (fette) di un array in modo veloce ed elegante:
* consente di selezionare più punti contemporaneamente, come un'intera riga, colonna o ogni terzo elemento di una riga o colonna.
* funziona come con le liste in Python, ma puoi applicarlo anche a matrici (array 2D) e array multidimensionali.

*La sintassi generale*\
`array[start:stop:step]`

+ start: indica l'indice iniziale (incluso).
+ stop: indica l'indice finale (escluso).
+ step: opzionale, indica quanti elementi saltare. 

In [233]:
import numpy as np

a = np.array([10, 20, 30, 40, 50, 60])

print(a[1:4])    # → [20 30 40]  (da indice 1 a 3)
print(a[:3])     # → [10 20 30]  (dall’inizio a indice 2)
print(a[::2])    # → [10 30 50]  (tutti gli elementi con passo 2)

[20 30 40]
[10 20 30]
[10 30 50]


In [234]:
b = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(b[0, :])    # → [1 2 3]  (tutta la prima riga)
print(b[:, 1])    # → [2 5 8]  (tutta la seconda colonna)
print(b[1:, 1:])  # → [[5 6] [8 9]] (parte inferiore destra)


[1 2 3]
[2 5 8]
[[5 6]
 [8 9]]


# Esercitazione
Data la matrice a:

In [236]:
a = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120]
])

1. Stampa tutte le righe, solo le prime due colonne
2. Stampa la seconda riga completa
3. Stampa l’ultimo elemento di ogni riga
4. Estrai il blocco centrale `[[60, 70], [100, 110]]`

|<br>
|<br>
|<br>
|<br>
|<br>

In [237]:
print("Prime due colonne di tutte le righe:\n", a[:, :2])
print("Seconda riga:", a[1, :])
print("Ultimo elemento di ogni riga:", a[:, -1])
print("Blocco centrale:\n", a[1:, 1:3])


Prime due colonne di tutte le righe:
 [[ 10  20]
 [ 50  60]
 [ 90 100]]
Seconda riga: [50 60 70 80]
Ultimo elemento di ogni riga: [ 40  80 120]
Blocco centrale:
 [[ 60  70]
 [100 110]]


In [238]:
unadim_array=np.arange(10)
unadim_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [239]:
unadim_array[2:6]

array([2, 3, 4, 5])

In [240]:
unadim_array[:5]

array([0, 1, 2, 3, 4])

In [241]:
unadim_array[-3]

7

In [242]:
unadim_array[-3:]

array([7, 8, 9])

In [243]:
unadim_array[::2]

array([0, 2, 4, 6, 8])

In [244]:
duedim_arr=np.reshape(np.arange(12),(3,4))
duedim_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [245]:
duedim_arr[1:,1:]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [246]:
duedim_arr[1,:]
#selezioniamo la seconda riga

array([4, 5, 6, 7])

In [247]:
duedim_arr[:,2]
#selezioniamo solo la terza colonna

array([ 2,  6, 10])

Lo slicing ha un comportamento molto diverso applicato alle liste rispetto agli ndarray.\

Per gli ndarray, il subarray generato fa riferimento all'area originale di memoria, crea una view (vista) sull'array originale, ovvero è solo un modo differente per accedere ai dati dell'array.

Modificando la view, viene modificato l'array originale. 

In [249]:
lista = [10, 20, 30, 40]
sub_lista = lista[1:3]
sub_lista[0] = 999

print("Lista originale:", lista)       # [10, 20, 30, 40]
print("Sottolista:", sub_lista)        # [999, 30]
# la lista originale non cambia

Lista originale: [10, 20, 30, 40]
Sottolista: [999, 30]


In [ ]:
import numpy as np

a = np.array([10, 20, 30, 40])
sub_array = a[1:3]
sub_array[0] = 999

print("Array originale:", a)           # [10 999 30 40]
print("Sub-array (view):", sub_array)  # [999  30]
# l'array originale viene modificato, perchè sub_array è una view, non una copia. 

* Le view sono più efficienti in memoria e velocità.
* Occorre fare attenzione: se modifichiamo la view, stiamo modificando l’originale.

# Esercitazione
1. Crea un array NumPy da 1 a 6
2. Fai slicing su `[2:5]`
3. Cambia il primo valore della slice
4. Verifica se l’array originale è cambiato

In [250]:
import numpy as np

# 1. Crea l’array da 1 a 6
a = np.array([1, 2, 3, 4, 5, 6])

# 2. Slice degli elementi da indice 2 a 4 → [3, 4, 5]
s = a[2:5]

# 3. Modifica il primo elemento della slice
s[0] = 999

# 4. Stampa array originale e slice
print("Slice modificata:", s)
print("Array originale modificato:", a)


Slice modificata: [999   4   5]
Array originale modificato: [  1   2 999   4   5   6]


# Unire e dividere gli array

Spesso dobbiamo unire array in un array più grande o dividerne uno grande in parti più piccole. Questo è utile quando preprocessiamo i dati e dobbiamo aggiungerli o combinarli più volte.

## Concatenate
`np.concatenate()`
* Unisce array lungo un asse (di default riga/asse 0)

In [251]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = np.concatenate((a, b))
print(c)  # [1 2 3 4 5 6]


[1 2 3 4 5 6]


In [253]:
import numpy as np

In [254]:
primo_array=np.arange(1,11)
secondo_array=np.arange(11,21)
print('Primo array', primo_array)
print('Secondo array', secondo_array)

Primo array [ 1  2  3  4  5  6  7  8  9 10]
Secondo array [11 12 13 14 15 16 17 18 19 20]


In [255]:
con_array=np.concatenate((primo_array, secondo_array))
con_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

La funzione concatenate accetta come parametri una sequenza di array e un secondo parametro opzionale, axis, che specifica l'asse lungo cui concatenare gli array. Se non viene specificato, l'asse predefinito è 0.

In [256]:
terzo_2darray=np.array([[1,2,3,4,5],[6,7,8,9,10]])
terzo_2darray


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [257]:
quarto_2darray=np.array([[11,12,13,14,15],[16,17,18,19,20]])
quarto_2darray

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [258]:
con2d_array=np.concatenate((terzo_2darray,quarto_2darray), axis=1)
con2d_array

array([[ 1,  2,  3,  4,  5, 11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10, 16, 17, 18, 19, 20]])

## Stack
Altra funzione simile a concatenate è `stack`, che unisce gli array lungo un nuovo asse:
* Utilizziamo stack sugli array unidimensionali first_arr e second_arr per creare un array bidimensionale:

In [259]:
st_array=np.stack((primo_array, secondo_array))
st_array

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

# Unione orizzontale e verticale

* `hstack`: unisce gli array orizzontalmente.
* `vstack`: unisce gli array verticalmente.

In [264]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

hstack = np.hstack((a, b))
print("hstack:", hstack)  # [1 2 3 4 5 6]

hstack: [1 2 3 4 5 6]


In [260]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

vstack = np.vstack((a, b))
print("vstack:\n", vstack)

vstack:
 [[1 2 3]
 [4 5 6]]


In [265]:
hst_arr=np.hstack((primo_array, secondo_array))
hst_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [266]:
vst_arr=np.vstack((primo_array, secondo_array)) #utilizziamo la pila su righe e colonne
vst_arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

# Dividere gli array

La divisione separa un array in più sottoarray. \
Questo può essere fatto utilizzando funzioni come split, array_split, hsplit e vsplit.

## Funzione `split`

* La funzione split ha un limite importante: può dividere gli array solo quando il numero di elementi è divisibile per il numero di divisioni. Altrimenti, genera un errore.
Le matrici risultanti devono avere la stessa forma. Altrimenti si restringerebbe.

In [267]:
a = np.array([10, 20, 30, 40, 50, 60])

parti = np.split(a, 3)  # 3 parti uguali
print("Split:", parti)
# divide array in più parti uguali

Split: [array([10, 20]), array([30, 40]), array([50, 60])]


In [268]:
matrice = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])

v_parti = np.vsplit(matrice, 2)
print("vsplit:", v_parti)
# split verticale (righe) 

vsplit: [array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


In [270]:
matrice = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

h_parti = np.hsplit(matrice, 2)
print("hsplit:", h_parti)
# slip orizzontale (colonne)

hsplit: [array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]


In [271]:
quinto_array=np.arange(1,13)
quinto_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [272]:
sp_array=np.array_split(quinto_array,4)
sp_array

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]

In [273]:
print(sp_array[1])

[4 5 6]


Se vogliamo dividere un array con un numero di elementi non divisibile, array_split gestisce automaticamente la divisione.

In [274]:
sp_array=np.array_split(quinto_array,8)
sp_array

[array([1, 2]),
 array([3, 4]),
 array([5, 6]),
 array([7, 8]),
 array([9]),
 array([10]),
 array([11]),
 array([12])]

# Esercitazione

1. Crea due array 1D: `a = [10, 20, 30]` e `b = [40, 50, 60]`
2. Uniscili:
+ con concatenate()
+ con vstack()
3. Crea un array `[1, 2, 3, 4, 5, 6]` e dividilo in 3 parti
4. Crea una matrice 2D 4x2 e dividila in 2 blocchi verticali

|<br>
|<br>
|<br>
|<br>
|<br>

In [275]:
import numpy as np

# 1. Unione
a = np.array([10, 20, 30])
b = np.array([40, 50, 60])

concat = np.concatenate((a, b))
vst = np.vstack((a, b))

print("Concatenate:", concat)
print("vstack:\n", vst)

# 2. Split array 1D
arr = np.array([1, 2, 3, 4, 5, 6])
diviso = np.split(arr, 3)
print("Split in 3 parti:", diviso)

# 3. Split matrice 4x2
matrice = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
v_blocchi = np.vsplit(matrice, 2)
print("Split verticale (righe):", v_blocchi)


Concatenate: [10 20 30 40 50 60]
vstack:
 [[10 20 30]
 [40 50 60]]
Split in 3 parti: [array([1, 2]), array([3, 4]), array([5, 6])]
Split verticale (righe): [array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]
