# Operazioni aritmetiche
 NumPy ha una potente capacità di applicare operazioni sull'intero array anziché su ciascun elemento individualmente. Questo si chiama vettorizzazione.
 
Quando utilizzata in modo efficiente, la vettorizzazione elimina la necessità di molti cicli for espliciti.\
I benefici sono:

1. Codice più performante
1. Codice meno verboso
1. Maggiore manutenibilità


In [1]:
import numpy as np

In [2]:
a=np.arange(1,11)
b=np.arange(21,31)
print('a', a)
print('b', b)

a [ 1  2  3  4  5  6  7  8  9 10]
b [21 22 23 24 25 26 27 28 29 30]


In [3]:
a+b

array([22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

In [4]:
b-a

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20])

In [6]:
a*b

array([ 21,  44,  69,  96, 125, 156, 189, 224, 261, 300])

In [7]:
b/a

array([21.        , 11.        ,  7.66666667,  6.        ,  5.        ,
        4.33333333,  3.85714286,  3.5       ,  3.22222222,  3.        ])

In [5]:
c=np.arange(2,12)
print('c', c)

c [ 2  3  4  5  6  7  8  9 10 11]


In [6]:
a**c

array([           1,            8,           81,         1024,
              15625,       279936,      5764801,    134217728,
         3486784401, 100000000000])

In [7]:
a*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [8]:
a/2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

# `np.add(a,b)`
Esegue la somma elemento per elemento tra due array della stessa forma.

In [10]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

somma = np.add(a, b)
print("Somma con np.add:", somma)

Somma con np.add: [11 22 33]


In [11]:
np.add(a,b)

array([11, 22, 33])

# Esercitazione
1. Crea due array: `a = [5, 10, 15]` e `b = [2, 4, 6]`
2. Somma a e b con np.add()
3. Crea due array 2x2 e somma le matrici
4. Stampa i risultati

|<br>
|<br>
|<br>
|<br>
|<br>

In [12]:
import numpy as np

# 1. Somma array 1D
a = np.array([5, 10, 15])
b = np.array([2, 4, 6])
risultato1 = np.add(a, b)

# 2. Somma array 2D
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[10, 20], [30, 40]])
risultato2 = np.add(mat1, mat2)

print("Somma 1D:", risultato1)
print("Somma 2D:\n", risultato2)

Somma 1D: [ 7 14 21]
Somma 2D:
 [[11 22]
 [33 44]]


# `np.subtract(a,b)`
Esegue la sottrazione elemento per elemento tra due array della stessa forma.

In [13]:
import numpy as np

a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

diff = np.subtract(a, b)
print("Sottrazione con np.subtract:", diff)

Sottrazione con np.subtract: [ 9 18 27]


In [13]:
np.subtract(b,a)

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20])

In [14]:
mat1 = np.array([[5, 10], [15, 20]])
mat2 = np.array([[1, 2], [3, 4]])

ris = np.subtract(mat1, mat2)
print(ris)

[[ 4  8]
 [12 16]]


# Esercitazione 
1. Crea due array: `a = [100, 200, 300]` e `b = [10, 20, 30]`
2.Esegui la sottrazione a - b usando:
* `np.subtract()`
* l’operatore -
3. Crea due array 2x2 e sottrai mat2 da mat1
4. Stampa tutti i risultati

|<br>
|<br>
|<br>
|<br>
|<br>

In [15]:
import numpy as np

# 1. Array 1D
a = np.array([100, 200, 300])
b = np.array([10, 20, 30])

diff1 = np.subtract(a, b)
diff2 = a - b

print("np.subtract:", diff1)
print("Operatore - :", diff2)

# 2. Array 2D
mat1 = np.array([[10, 20], [30, 40]])
mat2 = np.array([[1, 2], [3, 4]])

diff_mat = np.subtract(mat1, mat2)
print("Sottrazione 2D:\n", diff_mat)

np.subtract: [ 90 180 270]
Operatore - : [ 90 180 270]
Sottrazione 2D:
 [[ 9 18]
 [27 36]]


# `np.multiply(a,b)`
Moltiplica elemento per elemento due array della stessa forma.

In [16]:
import numpy as np

a = np.array([2, 4, 6])
b = np.array([10, 20, 30])

prodotto = np.multiply(a, b)
print("np.multiply:", prodotto)

np.multiply: [ 20  80 180]


In [17]:
np.multiply(a,b)

array([ 20,  80, 180])

In [18]:
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[10, 20], [30, 40]])

ris = np.multiply(mat1, mat2)
print("Moltiplicazione 2D:\n", ris)

Moltiplicazione 2D:
 [[ 10  40]
 [ 90 160]]


# Esercitazione 
1. Crea due array: `a = [1, 3, 5]` e `b = [2, 4, 6]`
2. Calcola il prodotto elemento per elemento con:
* np.multiply()
* l’operatore *
3. Crea due array 2D 2x2 e calcola la moltiplicazione elemento per elemento.

|<br>
|<br>
|<br>
|<br>
|<br>

In [19]:
import numpy as np

# 1. Array 1D
a = np.array([1, 3, 5])
b = np.array([2, 4, 6])

prod1 = np.multiply(a, b)
prod2 = a * b

print("np.multiply:", prod1)
print("Operatore *:", prod2)

# 2. Array 2D
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[10, 20], [30, 40]])

prod_mat = np.multiply(mat1, mat2)
print("Moltiplicazione 2D:\n", prod_mat)


np.multiply: [ 2 12 30]
Operatore *: [ 2 12 30]
Moltiplicazione 2D:
 [[ 10  40]
 [ 90 160]]


# `np.divide(a,b)`
Divisione elemento per elemento

In [24]:
import numpy as np

a = np.array([10, 20, 30])
b = np.array([2, 4, 5])

ris = np.divide(a, b)
print("Divide:", ris)

Divide: [5. 5. 6.]


# `np.mod(a,b)`
Resto della divisione (modulo)

In [22]:
a = np.array([10, 20, 30])
b = np.array([3, 6, 7])

ris = np.mod(a, b)
print("Modulo:", ris)

Modulo: [1 2 2]


# `np.power(a,b)`
Potenza elemento per elemento

In [25]:
a = np.array([2, 3, 4])
b = np.array([3, 2, 1])

ris = np.power(a, b)
print("Potenza:", ris)

Potenza: [8 9 4]


# `np.sqrt(a)`
Radice quadrata elemento per elemento

In [26]:
a = np.array([4, 9, 16])

ris = np.sqrt(a)
print("Radice quadrata:", ris)

Radice quadrata: [2. 3. 4.]


# Esercitazione
1. Crea due array `a = [9, 16, 25]` e `b = [3, 4, 5]`
2. Calcola:
* la divisione a / b
* il modulo a % b
* la potenza a^b
* la radice quadrata di a
3. Stampa tutti i risultati

|<br>
|<br>
|<br>
|<br>
|<br>
|<br>

In [30]:
import numpy as np

a = np.array([9, 16, 25])
b = np.array([3, 4, 5])

div = np.divide(a, b)
mod = np.mod(a, b)
pot = np.power(a, b)
rad = np.sqrt(a)

print("Divisione:", div)
print("Modulo:", mod)
print("Potenza:", pot)
print("Radice quadrata:", rad)

Divisione: [3. 4. 5.]
Modulo: [0 0 0]
Potenza: [    729   65536 9765625]
Radice quadrata: [3. 4. 5.]


# Casting
Il type casting converte il tipo di dato di un array.

# `.astype()`

In [32]:
import numpy as np

a = np.array([1, 2, 3])
b = a.astype(float)

print("Array intero:", a)
print("Array float:", b)
print("Tipo:", b.dtype)

Array intero: [1 2 3]
Array float: [1. 2. 3.]
Tipo: float64


# Broadcasting

A volte è necessario applicare operazioni aritmetiche su array di forme e dimensioni diverse.
> NumPy ci permette di farlo utilizzando un meccanismo chiamato **broadcasting**. 

Quando gli array hanno dimensioni diverse, le operazioni aritmetiche possono essere eseguite se l'array più piccolo può essere espanso per corrispondere all'array più grande, seguendo regole semplici.

### Come funziona
Il broadcasting segue regole semplici per determinare se possiamo applicare operazioni aritmetiche su array:

1. Si parte confrontando le dimensioni a partire dall'ultima dimensione di ciascun array.
1. Le dimensioni sono compatibili se:
+ Gli assi hanno la stessa lunghezza.
+ Uno degli assi ha lunghezza 1 (e quindi può essere espanso).


In [33]:
import numpy as np

# Compatibili

* `a` è un array 2D con forma `(3,3)`.

In [34]:
a=np.arange(1,10).reshape(3,3) # matrice 3x3 con valori da 1 a 9 
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

`b` è un arrat 1D con 3 elementi.

In [37]:
b=np.arange(1,4) # array 1D con 3 elementi 
b

array([1, 2, 3])

Quando facciamo a + b, NumPy applica broadcasting riga per riga:

> La riga `[1 2 3]` viene applicata a ogni riga di `a`.

In [38]:
a+b 

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

NumPy ha espanso l'array b lungo l'asse verticale per corrispondere alla forma di a e poi ha eseguito l'addizione elemento per elemento.

### Il broadcasting funziona perché:

* `a` ha forma `(3, 3)`
* `b` ha forma `(3,)`, che viene trasformata automaticamente in `(1, 3)`

# Esercizio
1. Crea un array `a = np.ones((4, 3))`
2. Crea `b = np.array([10, 20, 30])`
3. Calcola `a + b` con broadcasting
4. Stampa risultato e forma

|<br>
|<br>
|<br>
|<br>

In [39]:
import numpy as np

# 1. Array 4x3 di soli 1
a = np.ones((4, 3))
print("Array a (4x3):\n", a)

# 2. Array 1D di 3 elementi
b = np.array([10, 20, 30])
print("\nArray b (1D):", b)

# 3. Somma con broadcasting
c = a + b
print("\nRisultato a + b:\n", c)

# 4. Forme
print("\nForma di a:", a.shape)
print("Forma di b:", b.shape)
print("Forma del risultato:", c.shape)


Array a (4x3):
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Array b (1D): [10 20 30]

Risultato a + b:
 [[11. 21. 31.]
 [11. 21. 31.]
 [11. 21. 31.]
 [11. 21. 31.]]

Forma di a: (4, 3)
Forma di b: (3,)
Forma del risultato: (4, 3)


# Broadcasting non compatibile
Il broadcasting funziona solo se, confrontando le forme da destra verso sinistra:
* le dimensioni sono uguali, oppure;
* una delle due vale 1.

* `a.shape = (3, 4)`
* `b.shape = (2,)` \
Non sono compatibili perché 4 ≠ 2 e nessuna dimensione è 1.

In [ ]:
import numpy as np

a = np.ones((3, 4))    # matrice 3 righe, 4 colonne
b = np.array([10, 20]) # array 1D con 2 elementi

# Proviamo la somma
c = a + b  # ← ERRORE


In [17]:
d=np.arange(24).reshape(2,3,4) #3D:2x3x4
d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

## Statistiche riassuntive
Quando ci troviamo di fronte a una grande quantità di dati, uno dei primi passi è calcolare le statistiche riassuntive per analizzare i dati.

NumPy ci aiuta in questo con una serie di funzioni per calcolare aggregati sugli array. 

Queste funzioni accettano un array come input e, di default, restituiscono uno scalare come output. \
Questi calcoli includono medie, deviazione standard, somma e prodotto degli elementi di un array.

In [41]:
import numpy as np

In [42]:
primo_arr=np.arange(10,110,10)
primo_arr

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [43]:
secondo_arr=np.arange(10, 100,10).reshape(3,3)
secondo_arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [44]:
terzo_arr=np.arange(10,110,10).reshape(2,5)
terzo_arr

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [45]:
primo_arr.sum()

550

In [46]:
secondo_arr.sum()

450

In [28]:
terzo_arr.sum()

550

## Somma per colonne o righe

Per calcolare la somma di ogni colonna o riga di un array, usiamo il parametro axis:
* Colonne: `axis=0`
* Righe: `axis=1`

In [47]:
secondo_arr.sum(axis=0) #somma di ogni colonna

array([120, 150, 180])

In [48]:
secondo_arr.sum(axis=1) #somma di ogni riga

array([ 60, 150, 240])

# Prodotto di tutti elementi di un array (non tra array)
Calcola il prodotto di tutti gli elementi di un array, o lungo un asse specifico.

In [49]:
primo_arr.prod()

36288000000000000

In [50]:
secondo_arr.prod()

362880000000000

In [34]:
terzo_arr.prod()

36288000000000000

In [35]:
terzo_arr.prod(axis=0)

array([ 600, 1400, 2400, 3600, 5000])

# `np.dot()` – Prodotto scalare o matriciale
Esegue il prodotto tra due array:

* prodotto scalare se array 1D
* prodotto matriciale se array 2D

In [51]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.dot(a, b))  # → 1×4 + 2×5 + 3×6 = 32

32


In [52]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(np.dot(A, B))

[[19 22]
 [43 50]]


# Esercitazione
1. Crea un array 1D `a = [2, 4, 6]`
2. Calcola:
* il prodotto totale con np.prod()
* il prodotto scalare con se stesso usando np.dot()
3. Crea due array 2x2 e calcola il prodotto matriciale

In [53]:
import numpy as np

# Array 1D
a = np.array([2, 4, 6])

print("Prodotto totale:", np.prod(a))      # → 48
print("Prodotto scalare:", np.dot(a, a))   # → 2² + 4² + 6² = 56

# Array 2D
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Prodotto matriciale:\n", np.dot(A, B))


Prodotto totale: 48
Prodotto scalare: 56
Prodotto matriciale:
 [[19 22]
 [43 50]]


## Media degli elementi
La funzione `average` restituisce la media di un array. \
Possiamo anche specificare un asse per ottenere la media per colonne o righe

In [54]:
np.average(primo_arr)

55.0

In [55]:
np.average(secondo_arr)

50.0

In [56]:
np.average(terzo_arr)

55.0

# Valore minimo e massimo

In [57]:
np.min(primo_arr)

10

In [58]:
np.max(primo_arr)

100

## Media e deviazione standard
La deviazione standard è la misura della dispersione dei dati dalla media, è un indice di variabilità. 

In [59]:
print(primo_arr)

[ 10  20  30  40  50  60  70  80  90 100]


In [60]:
np.mean(primo_arr)

55.0

In [62]:
np.std(primo_arr)

28.722813232690143

## Come ottenere elementi unici e conteggi
NumPy fornisce la funzione unique per trovare gli elementi unici in un array. Per ottenere gli elementi unici, basta passare il nome dell'array come argomento.

Con la funzione `unique`, possiamo identificare:

1. Gli elementi unici di un array.
1. Le righe e colonne uniche in array bidimensionali.
1. La posizione degli indici degli elementi unici.
1. Il conteggio delle frequenze degli elementi unici.

In [63]:
import numpy as np

In [64]:
primo_r=np.array([1,2,3,4,5,6,1,2,7,2,1,10,7,8])

In [65]:
np.unique(primo_r)

array([ 1,  2,  3,  4,  5,  6,  7,  8, 10])

In [66]:
secondo_r=np.array([[1,1,2,1],[3,1,2,1],[1,1,2,1],[7,1,1,1]])
secondo_r

array([[1, 1, 2, 1],
       [3, 1, 2, 1],
       [1, 1, 2, 1],
       [7, 1, 1, 1]])

In [67]:
np.unique(secondo_r)

array([1, 2, 3, 7])

In [68]:
np.unique(secondo_r, axis=0)

array([[1, 1, 2, 1],
       [3, 1, 2, 1],
       [7, 1, 1, 1]])

In [69]:
np.unique(secondo_r, axis=1)

array([[1, 1, 2],
       [1, 3, 2],
       [1, 1, 2],
       [1, 7, 1]])

### Posizioni degli indici degli elementi unici


In [59]:
primo_r=np.array([1,2,3,4,5,6,1,2,7,2,1,10,7,8])

In [60]:
np.unique(primo_r, return_index=True)

(array([ 1,  2,  3,  4,  5,  6,  7,  8, 10]),
 array([ 0,  1,  2,  3,  4,  5,  8, 13, 11]))

Il primo array restituito contiene gli elementi unici, mentre il secondo array contiene le posizioni degli indici di questi elementi unici nell'array originale.

### Conteggio delle frequenze degli elementi unici

In [62]:
secondo_r=np.array([[1,1,2,1],[3,1,2,1],[1,1,2,1],[7,1,1,1]])

In [63]:
np.unique(secondo_r, return_counts=True)

(array([1, 2, 3, 7]), array([11,  3,  1,  1]))

## Operazioni simili alla trasposizione

Abbiamo imparato come modificare la forma di un array utilizzando la funzione reshape. 

Ora esploriamo altre funzioni per operazioni simili alla trasposizione: `transpose`, `moveaxis` e s`wapaxes`.

Un aspetto importante è comprendere la differenza tra reshape e transpose:

+ La funzione reshape prende un array di input e lo trasforma nella forma desiderata.
+ La funzione transpose scambia righe e colonne, invertendo gli assi.


In [71]:
import numpy as np

In [72]:
first_2dimarray=np.arange(12).reshape((3,4))
first_2dimarray

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## Funzione `transpose`
La funzione `transpose` accetta due parametri:

1. L'array di input.
1. Gli assi da invertire (opzionale).

Restituisce un array con gli assi invertiti: righe e colonne vengono scambiate. 

In [73]:
np.transpose(first_2dimarray)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [74]:
second_2darray=np.arange(6).reshape(3,2)
second_2darray

array([[0, 1],
       [2, 3],
       [4, 5]])

In [75]:
np.transpose(second_2darray,(1,0))

array([[0, 2, 4],
       [1, 3, 5]])

In [76]:
first_3dimarr=np.arange(24).reshape(2,3,4)
first_3dimarr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

## Funzione `moveaxis`
La funzione `moveaxis` sposta un asse di un array in una nuova posizione. Accetta tre parametri:

1. L'array di input.
1. La posizione sorgente dell'asse da spostare.
1. La posizione di destinazione per l'asse spostato.

In [77]:
np.moveaxis(first_3dimarr, 0,-1)

array([[[ 0, 12],
        [ 1, 13],
        [ 2, 14],
        [ 3, 15]],

       [[ 4, 16],
        [ 5, 17],
        [ 6, 18],
        [ 7, 19]],

       [[ 8, 20],
        [ 9, 21],
        [10, 22],
        [11, 23]]])

## Funzione `swapaxes`
La funzione `swapaxes` scambia due assi specifici di un array. \
Accetta tre parametri:

1. L'array di input.
1. Il primo asse da scambiare.
1. Il secondo asse da scambiare.

In [79]:
np.swapaxes(first_3dimarr, 0,2)

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

Dopo aver applicato swapaxes, i numeri vengono scambiati tra l'asse 0 e l'asse 2. \
La forma dell'array risultante è diventata 4x3x2.