In [1]:
# 8. NUMPY - Ripasso ed Esercizi

import numpy as np

## PARTE 1: RIPASSO (3 minuti)

### Creazione array

# Da lista
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])  # 2D

# Funzioni di creazione
zeros = np.zeros((3, 4))          # Matrice 3x4 di zeri
ones = np.ones((2, 3))            # Matrice 2x3 di uni
eye = np.eye(3)                   # Matrice identità 3x3
arange = np.arange(0, 10, 2)     # [0, 2, 4, 6, 8]
linspace = np.linspace(0, 1, 5)  # 5 punti tra 0 e 1
random = np.random.rand(3, 3)    # Matrice 3x3 casuale [0,1)

# Tipi di dati
int_arr = np.array([1, 2, 3], dtype=np.int32)
float_arr = np.array([1, 2, 3], dtype=np.float64)

### Attributi degli array

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr.shape)    # (2, 3) - dimensioni
print(arr.size)     # 6 - numero totale elementi
print(arr.ndim)     # 2 - numero dimensioni
print(arr.dtype)    # tipo dati

### Indicizzazione e slicing

# Array 1D
arr1d = np.array([10, 20, 30, 40, 50])
print(arr1d[0])      # 10
print(arr1d[-1])     # 50
print(arr1d[1:4])    # [20, 30, 40]

# Array 2D
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

print(arr2d[0, 1])   # 2 - riga 0, colonna 1
print(arr2d[1, :])   # [4, 5, 6] - riga 1 completa
print(arr2d[:, 2])   # [3, 6, 9] - colonna 2 completa
print(arr2d[0:2, 1:3])  # Sottomatrice

# Boolean indexing
arr = np.array([1, 2, 3, 4, 5])
mask = arr > 3
print(arr[mask])     # [4, 5]

### Operazioni matematiche

a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

# Operazioni elemento per elemento
print(a + b)         # [11, 22, 33, 44]
print(a * b)         # [10, 40, 90, 160]
print(a ** 2)        # [1, 4, 9, 16]

# Funzioni matematiche
print(np.sqrt(a))    # Radice quadrata
print(np.exp(a))     # Esponenziale
print(np.log(a))     # Logaritmo naturale
print(np.sin(a))     # Seno

# Aggregazioni
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.sum(arr))        # 21 - somma totale
print(np.sum(arr, axis=0)) # [5, 7, 9] - somma per colonne
print(np.sum(arr, axis=1)) # [6, 15] - somma per righe
print(np.mean(arr))       # 3.5 - media
print(np.std(arr))        # Deviazione standard
print(np.min(arr))        # 1
print(np.max(arr))        # 6

### Reshaping e manipolazione

# Reshape
arr = np.arange(12)
reshaped = arr.reshape(3, 4)    # Da 1D a 2D
reshaped2 = arr.reshape(2, 2, 3) # Da 1D a 3D

# Flatten e ravel
flat = reshaped.flatten()  # Copia appiattita
ravel = reshaped.ravel()   # Vista appiattita

# Transpose
transposed = reshaped.T

# Concatenazione
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
v_concat = np.vstack((a, b))  # Verticale
h_concat = np.hstack((a, b))  # Orizzontale

### Broadcasting

# Scalare con array
arr = np.array([1, 2, 3])
print(arr + 10)  # [11, 12, 13]

# Array di dimensioni compatibili
a = np.array([[1], [2], [3]])  # 3x1
b = np.array([10, 20, 30])     # 1x3
print(a + b)  # Broadcasting produce 3x3

(2, 3)
6
2
int64
10
50
[20 30 40]
2
[4 5 6]
[3 6 9]
[[2 3]
 [5 6]]
[4 5]
[11 22 33 44]
[ 10  40  90 160]
[ 1  4  9 16]
[1.         1.41421356 1.73205081 2.        ]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[0.         0.69314718 1.09861229 1.38629436]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
21
[5 7 9]
[ 6 15]
3.5
1.707825127659933
1
6
[11 12 13]
[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [ ]:
### Esercizio 1: Statistiche di matrice
# Calcola statistiche per righe e colonne di una matrice
def analizza_matrice(matrice):
    """
    Restituisce un dizionario con:
    - media per riga
    - media per colonna
    - elemento massimo e sua posizione
    - elemento minimo e sua posizione
    """
    # Il tuo codice qui:
    pass

# Test
mat = np.array([[1, 5, 3],
                [4, 2, 6],
                [7, 8, 9]])
print(analizza_matrice(mat))


### Esercizio 2: Operazioni con maschere
# Normalizza valori in un range e sostituisci outlier
def normalizza_e_pulisci(arr, min_val=0, max_val=1, percentile_basso=5, percentile_alto=95):
    """
    Normalizza array in [min_val, max_val] e sostituisce
    valori sotto/sopra i percentili con la mediana
    """
    # Il tuo codice qui:
    pass

# Test
dati = np.random.normal(50, 15, 100)
dati[0] = 200  # Outlier
dati[1] = -50  # Outlier
puliti = normalizza_e_pulisci(dati)
print(f"Range originale: [{dati.min():.1f}, {dati.max():.1f}]")
print(f"Range pulito: [{puliti.min():.1f}, {puliti.max():.1f}]")


### Esercizio 3: Manipolazione immagini
# Simula operazioni base su immagine (array 3D)
def processa_immagine(img):
    """
    img è un array 3D (altezza, larghezza, canali RGB)
    Restituisce dizionario con:
    - grayscale: versione in scala di grigi
    - flipped_h: ribaltata orizzontalmente
    - brightness: aumentata luminosità del 20%
    """
    # Il tuo codice qui:
    pass

# Test
img_test = np.random.rand(4, 4, 3)  # Piccola "immagine" 4x4
risultati = processa_immagine(img_test)
print("Forme risultati:")
for k, v in risultati.items():
    print(f"{k}: {v.shape}")


### Esercizio 4: Calcolo vettorizzato
# Implementa k-means clustering (versione semplificata)
def kmeans_semplice(punti, k=3, iterazioni=10):
    """
    punti: array Nx2 di coordinate
    k: numero di cluster
    Restituisce centroidi finali e assegnazioni
    """
    # Il tuo codice qui:
    pass

# Test
# Genera punti di test
np.random.seed(42)
cluster1 = np.random.randn(30, 2) + [0, 0]
cluster2 = np.random.randn(30, 2) + [5, 5]
cluster3 = np.random.randn(30, 2) + [0, 5]
punti = np.vstack([cluster1, cluster2, cluster3])

centroidi, assegnazioni = kmeans_semplice(punti, k=3)
print(f"Centroidi trovati:\n{centroidi}")


In [2]:
### Soluzione Esercizio 1:
def analizza_matrice(matrice):
    risultati = {}
    
    # Medie
    risultati['media_righe'] = np.mean(matrice, axis=1)
    risultati['media_colonne'] = np.mean(matrice, axis=0)
    
    # Massimo
    max_val = np.max(matrice)
    max_pos = np.argmax(matrice)
    max_riga, max_col = np.unravel_index(max_pos, matrice.shape)
    risultati['max'] = {'valore': max_val, 'posizione': (max_riga, max_col)}
    
    # Minimo
    min_val = np.min(matrice)
    min_pos = np.argmin(matrice)
    min_riga, min_col = np.unravel_index(min_pos, matrice.shape)
    risultati['min'] = {'valore': min_val, 'posizione': (min_riga, min_col)}
    
    return risultati

# Test
mat = np.array([[1, 5, 3],
                [4, 2, 6],
                [7, 8, 9]])
print(analizza_matrice(mat))

### Soluzione Esercizio 2:
def normalizza_e_pulisci(arr, min_val=0, max_val=1, percentile_basso=5, percentile_alto=95):
    # Copia per non modificare originale
    arr_copia = arr.copy()
    
    # Calcola percentili e mediana
    p_basso = np.percentile(arr_copia, percentile_basso)
    p_alto = np.percentile(arr_copia, percentile_alto)
    mediana = np.median(arr_copia)
    
    # Sostituisci outlier con mediana
    arr_copia[arr_copia < p_basso] = mediana
    arr_copia[arr_copia > p_alto] = mediana
    
    # Normalizza
    arr_min = arr_copia.min()
    arr_max = arr_copia.max()
    
    if arr_max - arr_min > 0:
        arr_norm = (arr_copia - arr_min) / (arr_max - arr_min)
        arr_norm = arr_norm * (max_val - min_val) + min_val
    else:
        arr_norm = np.full_like(arr_copia, (min_val + max_val) / 2)
    
    return arr_norm

# Test
dati = np.random.normal(50, 15, 100)
dati[0] = 200  # Outlier
dati[1] = -50  # Outlier
puliti = normalizza_e_pulisci(dati)
print(f"Range originale: [{dati.min():.1f}, {dati.max():.1f}]")
print(f"Range pulito: [{puliti.min():.1f}, {puliti.max():.1f}]")

### Soluzione Esercizio 3:
def processa_immagine(img):
    risultati = {}
    
    # Grayscale: media pesata dei canali RGB
    # Pesi standard: 0.299*R + 0.587*G + 0.114*B
    pesi = np.array([0.299, 0.587, 0.114])
    grayscale = np.dot(img, pesi)
    risultati['grayscale'] = grayscale
    
    # Flip orizzontale
    flipped_h = np.flip(img, axis=1)
    risultati['flipped_h'] = flipped_h
    
    # Aumenta luminosità del 20%
    brightness = img * 1.2
    # Clip per mantenere valori in [0, 1]
    brightness = np.clip(brightness, 0, 1)
    risultati['brightness'] = brightness
    
    return risultati

# Test
img_test = np.random.rand(4, 4, 3)
risultati = processa_immagine(img_test)
print("Forme risultati:")
for k, v in risultati.items():
    print(f"{k}: {v.shape}")

### Soluzione Esercizio 4:
def kmeans_semplice(punti, k=3, iterazioni=10):
    n_punti = punti.shape[0]
    
    # Inizializza centroidi casuali
    indici_casuali = np.random.choice(n_punti, k, replace=False)
    centroidi = punti[indici_casuali].copy()
    
    for _ in range(iterazioni):
        # Calcola distanze da ogni punto a ogni centroide
        distanze = np.zeros((n_punti, k))
        for i in range(k):
            # Distanza euclidea vettorizzata
            diff = punti - centroidi[i]
            distanze[:, i] = np.sqrt(np.sum(diff**2, axis=1))
        
        # Assegna ogni punto al centroide più vicino
        assegnazioni = np.argmin(distanze, axis=1)
        
        # Aggiorna centroidi
        for i in range(k):
            punti_cluster = punti[assegnazioni == i]
            if len(punti_cluster) > 0:
                centroidi[i] = np.mean(punti_cluster, axis=0)
    
    return centroidi, assegnazioni

# Test
np.random.seed(42)
cluster1 = np.random.randn(30, 2) + [0, 0]
cluster2 = np.random.randn(30, 2) + [5, 5]
cluster3 = np.random.randn(30, 2) + [0, 5]
punti = np.vstack([cluster1, cluster2, cluster3])

centroidi, assegnazioni = kmeans_semplice(punti, k=3)
print(f"Centroidi trovati:\n{centroidi}")

# Verifica risultati
for i in range(3):
    n_punti = np.sum(assegnazioni == i)
    print(f"Cluster {i}: {n_punti} punti")

{'media_righe': array([3., 4., 8.]), 'media_colonne': array([4., 5., 6.]), 'max': {'valore': np.int64(9), 'posizione': (np.int64(2), np.int64(2))}, 'min': {'valore': np.int64(1), 'posizione': (np.int64(0), np.int64(0))}}
Range originale: [-50.0, 200.0]
Range pulito: [0.0, 1.0]
Forme risultati:
grayscale: (4, 4)
flipped_h: (4, 4, 3)
brightness: (4, 4, 3)
Centroidi trovati:
[[ 4.98076258  5.07361111]
 [ 0.00816676  5.27302719]
 [-0.14415256 -0.1651568 ]]
Cluster 0: 29 punti
Cluster 1: 31 punti
Cluster 2: 30 punti
